language: ruby

rvm:
  - 2.5.5

branches:
  only:
  - source

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

script: bundle exec middleman build

deploy:
  local_dir: build/
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: master
